name: My KQM Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Python dependencies
        run: python3 -m pip install -r requirements.txt

      - name: Build
        run: |
          git config --global --add safe.directory $(pwd)
          qmk compile -kb sekigon/keyboard_quantizer/mini -km vial

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: kqm-firmware
          path: "*.uf2"
